--- 
- hosts: local
  vars:
    var1: hello
    var2: world
    my_dict:
        key1: zzzz
        key2: yyyy
        key3: whatever
    my_list:
        - hello
        - world
        - hello
        - world
        - hello
        - world
        - whatever
    my_list2:
        - world
        - 3
        - 77
        - Arista
    device: Cisco
        
  tasks:
    - name: Ternary operation
      debug:
        msg: "{{ (device == 'Cisco') | ternary('answer1', 'answer2') }}"

    - name: Cast string as boolean
      debug:
        msg: "{{ 'no' | bool }}"

    - name: Use regex_replace
      debug:
        msg: "{{ 'Some big string to parse' | regex_replace('^Some\\s+(big.*)$', '\\1 test') }}"

