--- 
- hosts: local
  vars:
    var1: hello
    var2: world
    my_dict:
        key1: zzzz
        key2: yyyy
        key3: whatever
    my_list:
        - hello
        - world
        - hello
        - world
        - hello
        - world
        - whatever
    my_list2:
        - world
        - 3
        - 77
        - Arista
    device: Cisco
        
  tasks:
    - name: Combine two dictionaries
      debug:
        msg: "{{ my_dict | combine({'key7': 'foo', 'key8': 'bar'}) }}"
      tags: combine

    - name: Extract values from a dict
      debug:
        msg: "{{ ['key1', 'key2'] | map('extract', my_dict) | list }}"
      tags: extract
