---
- name: IOS Config Change
  hosts: pynet-rtr1
  gather_facts: False
  vars:
    creds_ssh:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"

    name_server1: 8.8.8.8
    name_server2: 8.8.4.4
    default_domain: bogus1.com
    ntp1: 130.126.24.24
    ntp2: 152.2.21.1

    global_config:
      - "ip domain name {{ default_domain }}"
      - "ip name-server {{ name_server1 }}"
      - "ip name-server {{ name_server2 }}"
      - "ntp server {{ ntp1 }}"
      - "ntp server {{ ntp2 }}"
  tasks:
    - ios_config:
        provider: "{{ creds_ssh }}"
        lines: "{{ global_config }}"


- name: EOS Config Change
  hosts: pynet-sw7
  gather_facts: False
  vars:
    creds_eapi:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: eapi
      use_ssl: True
      validate_certs: no

    name_server1: 8.8.8.8
    name_server2: 8.8.4.4
    default_domain: bogus1.com
    ntp1: 130.126.24.24
    ntp2: 152.2.21.1

    global_config:
      - "ip domain-name {{ default_domain }}"
      - "ip name-server vrf default {{ name_server1 }}"
      - "ip name-server vrf default {{ name_server2 }}"
      - "ntp server {{ ntp1 }}"
      - "ntp server {{ ntp2 }}"
  tasks:
    - eos_config:
        provider: "{{ creds_eapi }}"
        lines: "{{ global_config }}"


- name: NXOS Config Change
  hosts: nxos2
  gather_facts: False
  vars:
    creds_ssh:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: cli
    creds_nxapi:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: nxapi
      use_ssl: yes
      validate_certs: no
      port: 8443

    name_server1: 8.8.8.8
    name_server2: 8.8.4.4
    default_domain: bogus1.com
    ntp1: 130.126.24.24
    ntp2: 152.2.21.1

    global_config:
      - "ip domain-name {{ default_domain }}"
      - "ip name-server {{ name_server1 }} {{ name_server2 }}"
      - "ntp server {{ ntp1 }}"
      - "ntp server {{ ntp2 }}"
  tasks:
    - nxos_config:
        provider: "{{ creds_nxapi }}"
        lines: "{{ global_config }}"
      tags: nxos

