---
- name: IOS Example
  hosts: cisco
  vars:
    creds:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
  tasks:
    - ios_facts:
        provider: "{{ creds }}"
      tags: facts_only

    - debug:
        var: ansible_net_model

    - ios_command:
        provider: "{{ creds }}"
        commands: show ip int brief
      register: output

    - debug:
        msg: "{{ output.stdout_lines[0] }}"
