---
# Construct a playbook using the ‘ios_facts’ module to connect to the two Cisco routers. Use the
# debug module to print out the two serial numbers.

- name: Gather facts (Cisco)
  gather_facts: no
  hosts: cisco
  vars:
    creds:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"

  tasks:
    - ios_facts:
        provider: "{{ creds }}"

    - debug:
        msg: "SN   {{ ansible_net_serialnum }}"

