---
- name: EOS Example
  hosts: pynet-sw1
  vars:
    ssh:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: cli

  tasks:
    - eos_facts:
        provider: "{{ ssh }}"

