---
- name: Configuration templating using include statement
  hosts: localhost
  gather_facts: false
  tasks:

  - name: Generate configuration files
    template: src=access_switch_1.j2 dest=CFGS/{{ item.hostname }}.txt
    with_items:
      - {hostname: pynet-sw1, default_gateway: 10.10.10.1,
         ip_addr: 10.10.10.10, netmask: 255.255.255.0}
      - {hostname: pynet-sw2, default_gateway: 10.10.20.1,
         ip_addr: 10.10.10.10, netmask: 255.255.255.0}
