---
- name: Test napalm replace 
  hosts: pynet-rtr1:pynet-sw5:srx1:nxos1
  tasks:
    - napalm_install_config:
        provider: "{{ creds }}"
        config_file: "CFGS/{{ inventory_hostname }}.txt"
        commit_changes: True
        replace_config: True
        diff_file: "DIFFS/{{ inventory_hostname }}.txt"
