---
- name: Generate Global Configuration Items (Part1)
  hosts: cisco:nxos:arista
  tasks:
    - name: Generate global configuration
      template:
        src: global_config.j2
        dest: "./CFGS/{{ inventory_hostname }}-global.txt"
      tags: 
        - ios
        - nxos
        - eos

- name: "Deploy configuration using Ansible Core (IOS): Part1b"
  hosts: cisco
  tasks:
    - ios_config:
        provider: "{{ creds_core_ssh }}"
        src: "./CFGS/{{ inventory_hostname }}-global.txt"
      tags: ios

- name: "Deploy configuration using Ansible Core (NX-OS): Part1b"
  hosts: nxos
  tasks:
    - nxos_config:
        provider: "{{ creds_core_nxapi }}"
        src: "./CFGS/{{ inventory_hostname }}-global.txt"
      tags: nxos

- name: "Deploy configuration using Ansible Core (Arista): Part1b"
  hosts: arista
  tasks:
    - eos_config:
        provider: "{{ creds_core_eapi }}"
        src: "./CFGS/{{ inventory_hostname }}-global.txt"
      tags: eos

