---
- name: Generate and Deploy BGP Configurations
  hosts: nxos
  tasks:
    - name: Generate BGP Configs (part2)
      template:
        src: bgp_ipv6.j2
        dest: "./CFGS/{{ inventory_hostname }}-bgp.txt"

    - name: "Push Configs using NAPALM: Merge (part2b)"
      napalm_install_config: 
        provider: "{{ creds_napalm }}"
        config_file: "./CFGS/{{ inventory_hostname }}-bgp.txt"
        commit_changes: True
        replace_config: False
        diff_file: "DIFFS/{{ inventory_hostname }}.txt"
